
###
GET http://localhost:8888/api/authority/r2
Authorization: Bearer {{auth_token}}
###

POST http://{{url}}/api/device/register?
    productName=tttest
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{auth_token}}

###
POST http://{{url}}/api/products
Content-Type: application/json
Authorization: {{auth_token}}

{
  "productName": "模拟器测试设备",
  "description": "模拟器测试设备"
}

###
GET http://{{url}}/api/products/{{productKey}}
Authorization: Bearer {{auth_token}}

###
GET http://{{url}}/api/products/user/list?
    page=0&
    size=2
Authorization: Bearer {{auth_token}}

###
DELETE http://{{url}}/api/products/{{productId}}
Authorization: Bearer {{auth_token}}

###
POST http://{{url}}/api/devices/register
Content-Type: application/json
Authorization: {{auth_token}}

{
  "deviceName": "simulator_dev",
  "nickName": "模拟器测试设备",
  "productKey": "yiEmvHjgVemX3V"
}


###
GET http://{{url}}/api/devices/product/list?
    productKey=efl4rbBGDN30Mg&
    page=1&
    size=2
Authorization: Bearer {{auth_token}}
